name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: |
         sudo chmod a+x script.sh
         sudo ./script.sh
         sudo mv lein /usr/local/bin/
         sudo chmod a+x /usr/local/bin/lein

  
