name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: |
         ls -ltrh
         sudo chmod a+x script.sh
         sudo ./script.sh
         lein version
         make test

  
